// Server generated by Zap v0.6.29 (https://github.com/red-blox/zap)
/**
 * @hidden
 */
export declare const sendEvents: () => void;
/**
 * @hidden
 */
export declare const SyncState: {
	fire: (
		player: Player,
		payload: {
			["data"]: {
				["backpackplus"]: {
					["backpack"]?:
						| Map<
								string,
								{
									["metadata"]?: Map<string, unknown> | undefined;
									["name"]?: string | undefined;
									["icon"]?: string | undefined;
									["tooltip"]?: string | undefined;
									["instance"]?: Tool | undefined;
								}
						  >
						| undefined;
					["equip"]?: string | undefined;
				};
			};
			["type"]: "init" | "patch";
		}[],
	) => void;
	fireAll: (
		payload: {
			["data"]: {
				["backpackplus"]: {
					["backpack"]?:
						| Map<
								string,
								{
									["metadata"]?: Map<string, unknown> | undefined;
									["name"]?: string | undefined;
									["icon"]?: string | undefined;
									["tooltip"]?: string | undefined;
									["instance"]?: Tool | undefined;
								}
						  >
						| undefined;
					["equip"]?: string | undefined;
				};
			};
			["type"]: "init" | "patch";
		}[],
	) => void;
	fireExcept: (
		except: Player,
		payload: {
			["data"]: {
				["backpackplus"]: {
					["backpack"]?:
						| Map<
								string,
								{
									["metadata"]?: Map<string, unknown> | undefined;
									["name"]?: string | undefined;
									["icon"]?: string | undefined;
									["tooltip"]?: string | undefined;
									["instance"]?: Tool | undefined;
								}
						  >
						| undefined;
					["equip"]?: string | undefined;
				};
			};
			["type"]: "init" | "patch";
		}[],
	) => void;
	fireList: (
		list: Player[] | Record<string | number | symbol, Player> | Map<unknown, Player>,
		payload: {
			["data"]: {
				["backpackplus"]: {
					["backpack"]?:
						| Map<
								string,
								{
									["metadata"]?: Map<string, unknown> | undefined;
									["name"]?: string | undefined;
									["icon"]?: string | undefined;
									["tooltip"]?: string | undefined;
									["instance"]?: Tool | undefined;
								}
						  >
						| undefined;
					["equip"]?: string | undefined;
				};
			};
			["type"]: "init" | "patch";
		}[],
	) => void;
	fireSet: (
		set: Set<Player> | Map<Player, unknown>,
		payload: {
			["data"]: {
				["backpackplus"]: {
					["backpack"]?:
						| Map<
								string,
								{
									["metadata"]?: Map<string, unknown> | undefined;
									["name"]?: string | undefined;
									["icon"]?: string | undefined;
									["tooltip"]?: string | undefined;
									["instance"]?: Tool | undefined;
								}
						  >
						| undefined;
					["equip"]?: string | undefined;
				};
			};
			["type"]: "init" | "patch";
		}[],
	) => void;
};
/**
 * @hidden
 */
export declare const RequestState: {
	on: (callback: (player: Player) => void) => () => void;
};
/**
 * @hidden
 */
export declare const RequestEquip: {
	on: (callback: (player: Player, toolId: string) => void) => () => void;
};
