// Client generated by Zap v0.6.29 (https://github.com/red-blox/zap)
export declare const sendEvents: () => void
export declare const SyncState: {
	setCallback: (callback: (payload: ({
		["data"]: {
			["backpackplus"]: {
				["backpack"]?: Map<string, {
					["metadata"]?: Map<string, unknown> | undefined,
					["name"]?: string | undefined,
					["icon"]?: string | undefined,
					["tooltip"]?: string | undefined,
					["instance"]?: Tool | undefined,
				}> | undefined,
				["equip"]?: string | undefined,
			},
		},
		["type"]: "init" | "patch",
	})[]) => void) => () => void;
};
export declare const RestoreLayout: {
	setCallback: (callback: (layout: {
		["hotbar"]: Map<string, string>,
		["order"]: (string)[],
	}) => void) => () => void;
};
export declare const RequestState: {
	fire: () => void;
};
export declare const RequestEquip: {
	fire: (toolId: string) => void;
};
export declare const ReportLayout: {
	fire: (layout: {
		["hotbar"]: Map<string, string>,
		["order"]: (string)[],
	}) => void;
};
