// Client generated by Zap v0.6.29 (https://github.com/red-blox/zap)
/**
 * @hidden
 */
export declare const sendEvents: () => void;
/**
 * @hidden
 */
export declare const SyncState: {
	setCallback: (
		callback: (
			payload: {
				["data"]: {
					["backpackplus"]: {
						["backpack"]?:
							| Map<
									string,
									{
										["metadata"]?: Map<string, unknown> | undefined;
										["name"]?: string | undefined;
										["icon"]?: string | undefined;
										["tooltip"]?: string | undefined;
										["instance"]?: Tool | undefined;
									}
							  >
							| undefined;
						["equip"]?: string | undefined;
					};
				};
				["type"]: "init" | "patch";
			}[],
		) => void,
	) => () => void;
};
/**
 * @hidden
 */
export declare const RequestState: {
	fire: () => void;
};
/**
 * @hidden
 */
export declare const RequestEquip: {
	fire: (toolId: string) => void;
};
